const questions = [
    { text: "Did your parents work nights and weekends to support your family?", value: -1 },
    { text: "Are you able to move through the world without fear of sexual assault?", value: 1 },
    { text: "Can you show affection for your romantic partner in public without fear of ridicule or violence?", value: 1 },
    { text: "Have you ever been diagnosed as having a physical or mental illness/disability?", value: -1 },
    { text: "Was the primary language spoken in your household growing up not the native language of the country where you were living?", value: -1 },
    { text: "Did you come from a supportive family environment?", value: 1 },
    { text: "Have you ever tried to change your speech or mannerisms to gain credibility?", value: -1 },
    { text: "Can you go anywhere in the country, and easily find the kinds of hair products you need and/or cosmetics that match your skin color?", value: 1 },
    { text: "Were you embarrassed about your clothes or house while growing up?", value: -1 },
    { text: "Can you make mistakes and not have people attribute your behavior to flaws in your racial/gender group?", value: 1 },
    { text: "Can you legally marry the person you love, regardless of where you live?", value: 1 },
    { text: "Were you born in the country where you live?", value: 1 },
    { text: "Have you or your parents ever gone through a divorce?", value: -1 },
    { text: "Did you feel like you had adequate access to healthy food growing up?", value: 1 },
    { text: "Are you reasonably sure you would be hired for a job based on your ability and qualifications?", value: 1 },
    { text: "Would you never think twice about calling the police when trouble occurs?", value: 1 },
    { text: "Can you see a doctor whenever you feel the need?", value: 1 },
    { text: "Do you feel comfortable being emotionally expressive/open?", value: 1 },
    { text: "Have you ever been the only person of your race/gender/socio-economic status/sexual orientation in a classroom or workplace setting?", value: -1 },
    { text: "Did you take out loans for your education?", value: -1 },
    { text: "Do you get time off for your religious holidays?", value: 1 },
    { text: "Did you have a job during your high school and college years?", value: -1 },
    { text: "Do you feel comfortable walking home alone at night?", value: 1 },
    { text: "Have you ever traveled outside the country where you were born?", value: 1 },
    { text: "Have you ever felt like there was NOT adequate or accurate representation of your racial group, sexual orientation group, gender group, and/or disability group in the media?", value: -1 },
    { text: "Do you feel confident that your parents would be able to financially help/support you if you were going through a financial hardship?", value: 1 },
    { text: "Have you ever been bullied or made fun of based on something that you can't change?", value: -1 },
    { text: "Were there more than 50 books in your house growing up?", value: 1 },
    { text: "Did you study the culture or the history of your ancestors in elementary school?", value: 1 },
    { text: "Did your parents or guardians attend college?", value: 1 },
    { text: "Did you ever go on a family vacation?", value: 1 },
    { text: "Can you buy new clothes or go out to dinner when you want to?", value: 1 },
    { text: "Were you ever offered a job because of your association with a friend or family member?", value: 1 },
    { text: "Was one of your parents ever laid off or unemployed not by choice?", value: -1 },
    { text: "Were you ever uncomfortable about a joke or a statement you overheard related to your race, ethnicity, gender, appearance, or sexual orientation but felt unsafe to confront the situation?", value: -1 }
];
